name: CI
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  build-and-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet restore CreditoSimuladoLite.sln
      - run: dotnet build CreditoSimuladoLite.sln --no-restore
      - run: dotnet test tests/Credito.Tests/Credito.Tests.csproj --no-restore
